IndiceAcademico/Controllers/EnrollmentsController.cs
using System.Linq;
using IndiceAcademico.Models;
using IndiceAcademico.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IndiceAcademico.Controllers
{
    [Authorize]
    public class EnrollmentsController : Controller
    {
        private readonly AcademicDBContext _context;
        public EnrollmentsController(AcademicDBContext context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult Index(int success = 0)
        {
            var enrollment = new Enrollments();

            ViewBag.students = _context.Students.ToList();
            ViewBag.subject = _context.Subjects.ToList();
            ViewBag.success = success;
            return View(enrollment);
        }
        [HttpPost]
        public IActionResult Index([Bind("SubjectId, StudentId")] Enrollments enrollments)
        {
            if (ModelState.IsValid)
            {
                _context.Enrollments.Add(enrollments);
                _context.SaveChanges();
                return RedirectToAction("Index", new { success = 1 });
            }

            return View(enrollments);
        }
        
        public IActionResult Qualify(int subjectId, int studentId, Score score)
        {
            var subject = _context.Subjects.FirstOrDefault(s => s.ID == subjectId);
            var student = _context.Students.FirstOrDefault(s => s.ID == studentId);
            Enrollments enrollments = new Enrollments { StudentId = studentId, SubjectId = subjectId, Score = score };
            _context.Enrollments.Update(enrollments);
            _context.SaveChanges();

            return View();
        }
    }
}

IndiceAcademico/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IndiceAcademico.Models;
using IndiceAcademico.Persistence;
using AutoMapper.QueryableExtensions;
using IndiceAcademico.Infraestructure.Dtos;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;

namespace IndiceAcademico.Controllers
{
    [Authorize(Roles = "Student, Professor")]
    
    public class StudentsController : Controller
    {
        private readonly AcademicDBContext _context;
        private readonly IMapper _mapper;

        public StudentsController(AcademicDBContext context, IMapper mapper)
        {
            _mapper = mapper;
            _context = context;
        }

        // GET: Students
        
        public async Task<IActionResult> Index()
        {
            return View(await _context.Students.ToListAsync());
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var student = await _context.Students
            .Include(e => e.Enrollments).ThenInclude(s => s.Subject).ProjectTo<StudentIndexDto>(_mapper.ConfigurationProvider).FirstOrDefaultAsync(s => s.ID == id);

            // var student = await _context.Students
            //     .FirstOrDefaultAsync(m => m.ID == id);
            // if (student == null)
            // {
            //     return NotFound();
            // }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Code,Name,LastName")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Code,Name,LastName")] Student student)
        {
            if (id != student.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.ID == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Students.FindAsync(id);
            _context.Students.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(int id)
        {
            return _context.Students.Any(e => e.ID == id);
        }
    }
}

IndiceAcademico/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IndiceAcademico.Models;
using IndiceAcademico.Persistence;
using Microsoft.AspNetCore.Identity;
using IndiceAcademico.Persistence.Identity;
using Microsoft.AspNetCore.Authorization;

namespace IndiceAcademico.Controllers
{
    [Authorize(Roles = "Professor")]
    public class SubjectController : Controller
    {

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly AcademicDBContext _context;

        public SubjectController(AcademicDBContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Subject
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.Users.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
            var subjects = await _context.Subjects.Where(s => s.ProfessorId == user.Id).ToListAsync();
            return View(subjects);
        }

        // GET: Subject/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var subjectNme =  _context.Subjects.FirstOrDefault(s => s.ID == id);
            ViewBag.SubjectName = subjectNme.Name.ToString();

            var students = await _context.Enrollments.Where(s => s.SubjectId == id).Include(s => s.Student).ToListAsync();

            //var subject = await _context.Subjects
            //    .Include(s => s.Professor)
            //    .FirstOrDefaultAsync(m => m.ID == id);
            //if (subject == null)
            //{
            //    return NotFound();
            //}

            return View(students);
        }

        // GET: Subject/Create
        public IActionResult Create()
        {
            ViewData["ProfessorId"] = new SelectList(_context.Professors, "ID", "LastName");
            return View();
        }

        // POST: Subject/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Code,Name,Cred,ProfessorId")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                _context.Add(subject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProfessorId"] = new SelectList(_context.Professors, "ID", "LastName", subject.ProfessorId);
            return View(subject);
        }

        // GET: Subject/Edit/5
        public async Task<IActionResult> Edit(int? subjectId, int? studentId)
        {
            if (subjectId == null)
            {
                return NotFound();
            }


            var subject = await _context.Subjects.FindAsync(subjectId);
            
            if (subject == null)
            {
                return NotFound();
            }
            //ViewData["ProfessorId"] = new SelectList(_context.Professors, "ID", "LastName", subject.ProfessorId);
            return View(subject);
        }

        // POST: Subject/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Code,Name,Cred,ProfessorId")] Subject subject)
        {
            if (id != subject.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(subject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubjectExists(subject.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProfessorId"] = new SelectList(_context.Professors, "ID", "LastName", subject.ProfessorId);
            return View(subject);
        }

        // GET: Subject/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .Include(s => s.Professor)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // POST: Subject/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subject = await _context.Subjects.FindAsync(id);
            _context.Subjects.Remove(subject);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SubjectExists(int id)
        {
            return _context.Subjects.Any(e => e.ID == id);
        }
    }
}

IndiceAcademico/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Indice Academico</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="@Url.Content("~/Logo.jpeg")"
                         alt="logo" width="75px">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Students"
                                   asp-action="Index">Estudiantes</a>
                            </li>
                            @if (User.IsInRole("Professor"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Professors"
                                       asp-action="Index">Profesores</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Subject"
                                       asp-action="Index">Signaturas</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Enrollments"
                                   asp-action="Index">Seleccion</a>
                            </li>
                        </ul>
                    </div>
                    <ul class="nav navbar-nav navbar-left">
                        <a class="btn btn-outline-danger  d-lg-inline-block my-2 my-md-0 ms-md-3" asp-area="" asp-controller="Account"
                           asp-action="Logout">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-power" viewBox="0 0 16 16">
                                <path d="M7.5 1v7h1V1h-1z" />
                                <path d="M3 8.812a4.999 4.999 0 0 1 2.578-4.375l-.485-.874A6 6 0 1 0 11 3.616l-.501.865A5 5 0 1 1 3 8.812z" />
                            </svg> Log out
                        </a>
                    </ul>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Weirds Programmers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>